comment: 
  layout: "reach, diff, flags, files"
  behavior: new
  require_changes: false
github_checks:
    annotations: false
coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 75%
        threshold: 0%
        if_ci_failed: error
        if_not_found: failure
    patch:
      default:
        target: 100%
        threshold: 0%
        if_ci_failed: error
        if_not_found: failure
    changes:
      default:
        target: 100%
        threshold: 0%
        if_ci_failed: error
        if_not_found: failure
    ignore:
      - "**/tests/*"