name: Workflow for Codecov
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  codecov-python-39:
    runs-on: windows-latest
    env:
      PYTHONTRACEMALLOC: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install coverage
      - name: Run tests and collect coverage
        run: |
          cd ./src/extension/tests
          echo '===============START EXTENSION TESTS...===============' >> ../../../err.txt
          coverage run -m unittest discover -s . -t ../../ 2>> ../../../err.txt
          echo '===============FINISH EXTENSION TESTS...===============' >> ../../../err.txt
          cd ../../core/tests
          echo '===============START CORE TESTS...===============' >> ../../../err.txt
          coverage run -m unittest discover -s . -t ../../ 2>> ../../../err.txt
          echo '===============FINISH CORE TESTS...===============' >> ../../../err.txt
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: python39
          name: python-39
          fail_ci_if_error: true
      - name: Read test output
        id: getoutput
        run: echo "::set-output name=contents::$(cat err.txt)"
      - name: Check if all tests passed
        if: contains( steps.getoutput.outputs.contents , 'FAILED (failures=' )
        run: |
          echo "${{ steps.getoutput.outputs.contents }}"
          exit 1
  codecov-python-27:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Install dependencies
        run: pip install coverage
      - name: Run tests and collect coverage
        run: |
          cd ./src/extension/tests
          echo '===============START EXTENSION TESTS...===============' >> ../../../err2.txt
          coverage run -m unittest discover -s . -t ../../ 2>> ../../../err2.txt
          echo '===============FINISH EXTENSION TESTS...===============' >> ../../../err2.txt
          cd ../../core/tests
          echo '===============START CORE TESTS...===============' >> ../../../err2.txt
          coverage run -m unittest discover -s . -t ../../ 2>> ../../../err2.txt
          echo '===============FINISH CORE TESTS...===============' >> ../../../err2.txt
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: python27
          name: python-27
          fail_ci_if_error: true
      - name: Read test output
        id: getoutput
        run: echo "::set-output name=contents::$(cat err2.txt)"
      - name: Check if all tests passed
        if: contains( steps.getoutput.outputs.contents, 'FAILED (failures=' )
        run: |
          echo "${{ steps.getoutput.outputs.contents }}"
          exit 1
