name: Workflow for Codecov
permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  codecov-python-312:
    runs-on: windows-latest
    env:
      PYTHONTRACEMALLOC: 1
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Set up Python 3.12
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install coverage
      - name: Run extension tests
        continue-on-error: true
        shell: cmd
        run: |
          cd ./src/extension/tests
          echo '===============START EXTENSION TESTS...===============' >> ../../../err.txt
          coverage run --append -m unittest discover -s . -t ../../ 2>> ../../../err.txt
          echo '===============FINISH EXTENSION TESTS...===============' >> ../../../err.txt
      - name: Run core tests
        continue-on-error: true
        shell: cmd
        run: |
          cd ./src/core/tests
          echo '===============START CORE TESTS...===============' >> ../../../err.txt
          coverage run --append -m unittest discover -s . -t ../../ 2>> ../../../err.txt
          echo '===============FINISH CORE TESTS...===============' >> ../../../err.txt
      - name: Collect coverage
        run: |
          cd ./src/core/tests
          coverage xml
          cd ../../extension/tests
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@4fe8c5f003fae66aa5ebb77cfd3e7bfbbda0b6b0 # v3.1.5
        with:
          flags: python312
          name: python-312
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Read test output and Check if all tests passed
        shell: bash
        run: |
          CONTENTS=$(cat err.txt)
          if echo "$CONTENTS" | grep -q 'FAILED (failures='; then
            echo "There are failed tests"
            echo "Contents: $CONTENTS"
            exit 1
          fi
  codecov-python-27:
    runs-on: windows-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    needs: codecov-python-312
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Restore Python 2.7 cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: C:\Python27
          key: python27-cache
      - name: Install Python 2.7
        shell: cmd
        run: |
          echo "check if python27 is not cached"
          if not exist C:\Python27 (
            choco install python2 -y
            SETX PATH "%PATH%;C:\Python27"
          )
      - name: Cache dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: '%UserProfile%\.cache\pip'
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        shell: cmd
        run: pip install -r .github/workflows/requirements.txt
      - name: Run extension tests
        continue-on-error: true
        shell: cmd
        run: |
          cd ./src/extension/tests
          echo '===============START EXTENSION TESTS...===============' >> ../../../err2.txt
          coverage run --append -m unittest discover -s . -t ../../ 2>> ../../../err2.txt
          echo '===============FINISH EXTENSION TESTS...===============' >> ../../../err2.txt
      - name: Run core tests
        continue-on-error: true
        shell: cmd
        run: |
          cd ./src/core/tests
          echo '===============START CORE TESTS...===============' >> ../../../err2.txt
          coverage run --append -m unittest discover -s . -t ../../ 2>> ../../../err2.txt
          echo '===============FINISH CORE TESTS...===============' >> ../../../err2.txt
      - name: Collect coverage
        run: |
          cd ./src/core/tests
          coverage xml
          cd ../../extension/tests
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@4fe8c5f003fae66aa5ebb77cfd3e7bfbbda0b6b0 # v3.1.5
        with:
          flags: python27
          name: python-27
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Read test output and Check if all tests passed
        shell: bash
        run: |
          CONTENTS=$(cat err2.txt)
          if echo "$CONTENTS" | grep -q 'FAILED (failures='; then
            echo "There are failed tests"
            echo "Contents: $CONTENTS"
            exit 1
          fi
